# Generated by Django 3.2.5 on 2021-07-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Textapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified_date',
            field=models.DateField(),
        ),
    ]
