# Generated by Django 3.2.5 on 2021-07-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Textapp', '0002_auto_20210714_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified_date',
            field=models.CharField(max_length=50),
        ),
    ]
