# Generated by Django 3.2.5 on 2021-07-14 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Textapp', '0006_auto_20210714_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
