# Generated by Django 3.2.5 on 2021-07-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Textapp', '0014_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
